### ISSUE TITLE
 self.onSwipeSuccess();

### ISSUE THREAD

**Issue by Mactub07** [sreejithr/react-native-slide-button#1]
self.onSwipeSuccess(); is not a function

**Comment by sreejithr** [comment]
@Mactub07 Thank you so much for bring this up. You're right. There's no such function called `onSwipeSuccess`. It's `onSlideSuccess`. I've changed it and have made a [pull request](https://github.com/sreejithr/react-native-slide-button/pull/2). This has been merged.

**Comment by Mactub07** [comment]
sound good!!! thanks
